### ISSUE TITLE
Add support for DRS URIs

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/DRS-cli#3]
For our integration in `cwl-WES`, what we will be dealing with is DRS URIs of the form `drs://<hostname>/<id>` (more info here: https://ga4gh.github.io/data-repository-service-schemas/preview/develop/docs/#_hostname_based_drs_uris). We could of course parse them in `cwl-WES` and then call the client as is, but I think it's more useful to implement parsing of these identifiers right in the client. So, if we encounter a DRS URI, we should be able to make use of it by passing it either to the _constructor_ or the request methods for the `GET` endpoints as a parameter, then relying on the client to handle them. We just have to make sure we find a solution that offers a nice user experience, i.e., the behavior for the user should be as consistent as possible with the use case in which we are manually passing host (to the constructor) and id (to the request methods).

> In principle port needs to be `443` for `HTTPS` (technically, port `80` isn't even allowed, because `HTTP` schema is not spec-compliant) in order for DRS URIs to work (because they don't support a port, unfortunately)
> But let's disregard that, because for development we don't always want to set up a SSL/TSL certificate

Probably the best would be to just extend the docstring for the constructor and request methods to allow a host name OR DRS URI (constructor) or an object ID OR DRS URI (request method), and then implement a static method that returns a tuple of host name and object ID when passed a DRS URI. Whether the user passes a DRS URI, we can easily detect by looking for the `drs://` prefix, as well as the presence of at least one `.` (from the hostname) and one more `/` (though depending on how the user sets the allowed charset for DRS object IDs in DRS-Filer, that is not guaranteed to be unambiguous, but we can just document in DRS-Filer, or perhaps better, enforce, that the character set should not/cannot include all of `:`, `/` and `.`).  Once we know we are dealing with a DRS URI in either the constructor or one of the request methods, we call the static method and then use either the host name (constructor) or object ID (request methods) in the same way we use them now.
So should be very easy to implement, just needs:
* a static method that detects a DRS URI via a regular expression (something like `^trs:\/\/\.+\.w+\/.+`; untested) and returns a `(host, id)` tuple if it is a DRS URI and returns `None` if it isn't;
* call that static method in the constructor and request methods with the passed `host` and `id`params, respectively
add some logic to check `if result is None` (in which case the original, unparsed value should be used for `host` and `id`, respectively) or `else` assign the first or second value of the resulting tuple to `host` or `id`, respectively
* add one more simple case each for constructor and request methods, this time passing a DRS URI
* add a couple of unit tests for the DRS URI detector/parser method, passing some valid and invalid DRS URIs

P.S: Directly copy pasted from Slack conversation

**Comment by uniqueg** [comment]
Added by #4
